### ISSUE TITLE
Wrong temperature output.

### ISSUE THREAD

**Issue by dyqi** [sparkfun/9DOF_Razor_IMU#11]
From document <<MPU-9250-Register-Map.pdf>>, there is  information below: 
"
        TEMP_degC = ((TEMP_OUT – RoomTemp_Offset)/Temp_Sensitivity)+ 21degC
        Where Temp_degC is the temperature in degrees C measured by the temperature sensor. 
        TEMP_OUT is the actual output of the temperature sensor.
"

    mpu_get_temperature function in "inv_mpu.c" file give a wrong temperature value, codes is below:
"
        data[0] = (long)((35 + ((raw - (float)st.hw->temp_offset) / st.hw->temp_sens)) * 65536L);
"

Why is there a "35" here ? It should be a bug.

**Comment by santaimpersonator** [comment]
I am not sure where you are getting this error:

> mpu_get_temperature function in "inv_mpu.c" file give a wrong temperature value, codes is below:

However, I believe that the 35 is for the **21degC** indicated by the register map. For further technical assistance with this product, please use our [forums](https://forum.sparkfun.com/index.php).
