### ISSUE TITLE
SPI pin for IMU M0

### ISSUE THREAD

**Issue by Manujaya94** [sparkfun/9DOF_Razor_IMU#15]
I have an  issue when runing the  Arduino -SPI library for IMU M0. Because in the datasheet there are no reference to identify SPI pins. Therefore can you help us to identify which pins are referenced for SPI protocol.

**Comment by bboyho** [comment]
Hi,

Try looking at my comment here for details => [https://github.com/sparkfun/9DOF_Razor_IMU/issues/14#issuecomment-413958078](https://github.com/sparkfun/9DOF_Razor_IMU/issues/14#issuecomment-413958078) .
