### ISSUE TITLE
What is the last data of SEN-14001? Razor 9DOF M0

### ISSUE THREAD

**Issue by h-jia** [sparkfun/9DOF_Razor_IMU#16]
The datasets:
`1996551, 0.01, 0.12, -1.00, 0.73, 0.38, 0.31, 12.15, -66.92, -45.91, 0.0369, -0.7548, -0.6537, -0.0402, 169.71`

I command `t+a+g+m+q `and it should be 1+3+3+3+4 = 14
While the datasets I received is 15. What is the last data?

Any suggestions would be much appreciated!

**Comment by santaimpersonator** [comment]
You probably have the compass heading set. For technical assistance with our products, please head over to our [forums](https://forum.sparkfun.com/index.php).
