### ISSUE TITLE
IMU does not detect in COM port

### ISSUE THREAD

**Issue by dibs06** [sparkfun/9DOF_Razor_IMU#17]
I have 2 Sparkfun MPU9250 ,first is connected with the arduino by itc I2C pin ,another one is connected with my PC via USB
Accidently I had upload Sparkfun MPU 9250 breakout program (which is connect with i2c in arduino) into the Saprkfun with DMP IMU(which is connect with the PC via USB).
Just after that it cannot detect in COM port.
What should I do?

**Comment by bboyho** [comment]
Hi,

If you are not able to see the 9DoF Razor IMU M0 anymore in your device manager, you can try to set it back by putting it in bootloader mode.  With any AVR device that has a built in CDC (i.e. the Atmega32U4 bootloaded with Arduino on the Pro Micro, FioV3, LilyPad Arduino USB, etc), there should be an option to place the board into bootloader mode if you brick the board. Try following the “Troubleshooting” note listed in the tutorial [ [https://learn.sparkfun.com/tutorials/9dof-razor-imu-m0-hookup-guide/all#installing-the-9dof-razor-arduino-core](https://learn.sparkfun.com/tutorials/9dof-razor-imu-m0-hookup-guide/all#installing-the-9dof-razor-arduino-core) ]:

> If your 9DoF Razor IMU won’t enter the bootloader, or take new code, you can force it into the bootloader by holding the SCL pin LOW on start up. Flip the IMU’s switch off, use a jumper wire to connect SCL to GND, and turn the switch back on. While in the bootloader, the blue pin 13 LED should remain illuminated.

You should then be able to upload the firmware [ [https://github.com/sparkfun/9DOF_Razor_IMU/blob/master/Firmware/_9DoF_Razor_M0_Firmware/_9DoF_Razor_M0_Firmware.ino]()https://github.com/sparkfun/9DOF_Razor_IMU/blob/master/Firmware/_9DoF_Razor_M0_Firmware/_9DoF_Razor_M0_Firmware.ino ] back to the SAMD21
