### ISSUE TITLE
dmpGetPedometerSteps values 

### ISSUE THREAD

**Issue by gretamosa** [sparkfun/9DOF_Razor_IMU#20]
I am using MPU9250_DMP_Pedometer example with Adafruit Feather M0.

Once compiled and uploaded the example into the board, I noticed that the walks number and their refresh interval into the serial monitor is so slow and I am not pretty sure that precise.

Anybody can help me? is it necessary calibrate the MPU9250 before or something like that?

Thanks in advanced,

**Comment by santaimpersonator** [comment]
Seeing as this is the repository for the SparkFun Razor IMU board, this issue might be better suited for the [DMP library](https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library).

That being said, make sure your hardware is set up properly for the Feather first. I tested the sketch and it seems to work fine on the SparkFun Razor IMU. From my testing, the sketch only outputs serial data when it registers steps. From experimenting, it looks like it needs some exaggerated strides to work (I had to jump up and down quite a few times. I found the sweet spot to be about 12-16" movements vertically at half-second intervals).

Unfortunately, I don't have a lot of insight into the pedometer feature as it is dependent on the DMP from Invensense and most of that code is "*black box"*.
