### ISSUE TITLE
Adding analog input to Logs

### ISSUE THREAD

**Issue by albertofast** [sparkfun/9DOF_Razor_IMU#21]
Dear all,
I bought the Sparkfun Razor imu m0 to compare its results with an industrial optical motion tracking system ( double integration to extract trajectory plus euler angles). The IMU will be used on a model falling in the air from about 3m height and then impacting on the water. I would like to add to my logs an analog input: a voltage signal ranging from 0 to 5v, sampled @100Hz like the rest of the imu data. As I am totally new to arduino  I kindly ask you a suggestion of how and where to modify the code to add the voltage read to the log file data output and to the serial monitor. 
Thank you!

**Comment by santaimpersonator** [comment]
Please refer to this [Arduino Analog Input Reference Page](https://www.arduino.cc/en/tutorial/AnalogInput). Also the logging section of the firmware can be found here:
https://github.com/sparkfun/9DOF_Razor_IMU/blob/master/Firmware/_9DoF_Razor_M0_Firmware/_9DoF_Razor_M0_Firmware.ino#L168

For further technical assistance with our products, please head over to our [forums](https://forum.sparkfun.com/index.php).
