### ISSUE TITLE
Increase the frequency more than 100 Hz

### ISSUE THREAD

**Issue by arkinrc** [sparkfun/9DOF_Razor_IMU#22]
Hello everybody, 
   I am working on this new Razor Imu M0 with SN14001. I want to use the sampling frequency around 200 hz and i tried many ways to change it however, more than 100 hz always got some errors on ros. i would strongly appreciate if someone have already solved this issue.  thanks .

**Comment by santaimpersonator** [comment]
Check out this issue, the user ended up increasing the speed on the I2C bus:

https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library/issues/12

**Comment by arkinrc** [comment]
Hi @santaimpersonator ok. thanks...
