### ISSUE TITLE
I2C scan

### ISSUE THREAD

**Issue by PhySan0111** [sparkfun/9DOF_Razor_IMU#23]
Dear all,

Recently I have acquired a 9DOF_Razor_IMU. I am currently trying to scan the i2c to check the addresses of the MPU9250, but if a run the i2c scanner the arduino does not print any addresses found. Does anybody know how can I scan the i2c from the 14001 9DOF_Razor_IMU board?

Best regards,
Miguel

**Comment by santaimpersonator** [comment]
Hi there, it sounds like you are looking for [technical assistance](https://www.sparkfun.com/technical_assistance). Please use the link, to get started with posting a topic in our [forums](https://forum.sparkfun.com/). Our technical support team will do their best to assist you.

In your forum post, it would probably help the TS team if you include a picture of your setup of how you have everything wired for the I2C scan.
