### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [sparkfun/9DOF_Razor_IMU#24]
In the file "9DOF_Razor_IMU/Libraries/Arduino/src/util/arduino_mpu9250_i2c.cpp", in the function "arduino_i2c_read()", there is a `Wire.endTransmission()` after a `Wire.requestFrom()`.

That `Wire.endTransmission()` is at the moment here: https://github.com/sparkfun/9DOF_Razor_IMU/blob/master/Libraries/Arduino/src/util/arduino_mpu9250_i2c.cpp#L46 and can be removed.

Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by santaimpersonator** [comment]
I am going to close this issue as the library used for the Arduino IDE actually lives here:

https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library

and the `Wire.endTransmission()` issue has already been taken care of.
