### ISSUE TITLE
IMU I2C address should be breakout

### ISSUE THREAD

**Issue by LucaCerina** [sparkfun/9DOF_Razor_IMU#26]
Hello,
I wanted to use the sparkfun Razor to record long-term accelerations. However, the default I2C address is 0x68 which conflicts with almost every decent I2C Real-Time Clock on the market.

I suggest that the default address should be changed to 0x69 or exposed with a small port on the breakout to be changed manually

**Comment by improve100** [comment]
i have the board that you want.



---Original---

**Comment by LucaCerina** [comment]
which one?
Luca Cerina
----------------
Graduate Research Assistant @ NECSTLab
DEIB (Dipartimento di Elettronica, Informazione e Bioingegneria)
Politecnico di Milano


Il giorno lun 7 ott 2019 alle ore 11:24 improve100 <notifications@github.com<mailto:notifications@github.com>> ha scritto:
i have the board that you want.



---Original---

**Comment by improve100** [comment]
i modify the board i2c adress 0x69. i have the same problem that you said



---Original---

**Comment by LucaCerina** [comment]
Of course I can rewire the circuit, but I would like to avoid the process on multiple samples just to have something that could be already available with an exposed soldering pad or something like that

**Comment by improve100** [comment]
i think you can jump wire.or buy the board that you want



---Original---

**Comment by nseidle** [comment]
OP - good point. We should have broken out the I2C address pin to a jumper or GPIO so that the user could change the IMU address. Unfortunately it's hard wired to 0x68. We'll try to fix this on a future rev.

As an aside, the SAMD21 is clocked with a 32.768kHz xtal. You may be able to setup an RTC function directly on the micro without the need for an external RTC.

**Comment by LucaCerina** [comment]
Fair enough, I will try also with that and see if the drift is ok.
