### ISSUE TITLE
SD Card logging 

### ISSUE THREAD

**Issue by nirvaanGarg** [sparkfun/9DOF_Razor_IMU#28]
The Sparkfun 9DOF_razor_imu that I have is not able to store the data on my sd Card which is a SanDisk Ultra 64GB MicroSDXC Class 10 Card. is there a problem with the SD card type or do i have to add any more firmware? Have added all libraries and firmware according to the setup guide

**Comment by nseidle** [comment]
If memory serves me correctly the SD library used only supports FAT32 with a limit of 32GB. Try a smaller card.
