### ISSUE TITLE
Mechanical Drawing

### ISSUE THREAD

**Issue by zshivers** [sparkfun/9DOF_Razor_IMU#30]
Can you provide a drawing for the overall dimensions, hole dimensions, and the IMU location / orientation? While this info is probably available within the eagle PCB files, it would be much more convenient for your users to publish as a PDF.

**Comment by santaimpersonator** [comment]
Unfortunately, this product has since been retired: https://www.sparkfun.com/products/retired/14001

Going forward, we are making an effort to publish dimensions for new boards. I will be closing this issue since users can download and look at the Eagle files.
