### ISSUE TITLE
How to get higher number of digits using Arduino library?

### ISSUE THREAD

**Issue by hurak** [sparkfun/9DOF_Razor_IMU#31]
Hi, trying the [MPU9250_Basic](https://github.com/sparkfun/9DOF_Razor_IMU/blob/master/Libraries/Arduino/examples/MPU9250_Basic/MPU9250_Basic.ino) example from the Arduino library, I can see (using the serial port monitor) that the measurements are sent from the unit with just four or even three digits of precision. Both the accelerometer and the magnetometer on MPU 9250 have 16-bit ADCs, which means that with the accelerometer returning values such as 1.23, the precision was unnecessarily significantly reduced, was not it? Is it possible to configure the library functions such that higher number of digits can be read from the IMU? Thanks.

**Comment by santaimpersonator** [comment]
Hi there, it sounds like you are looking for [technical assistance](https://www.sparkfun.com/technical_assistance). Please use the link, to get started with posting a topic in our [forums](https://forum.sparkfun.com/). Our technical support team will do their best to assist you.

That being said, please refer to the [documentation for the String function](https://www.arduino.cc/reference/en/language/variables/data-types/stringobject/).

As this doesn't seem to be an issue in the code, I will be closing it.
