### ISSUE TITLE
Compass heading wrong values

### ISSUE THREAD

**Issue by theonteg** [sparkfun/9DOF_Razor_IMU#8]
Compass heading values are not responding to reality in RAZOR IMU M0.
A full circle around z axis is changing heading values between 250 and 360 only... (should change respectively with the yaw value but it is not)

**Comment by santaimpersonator** [comment]
As described in this [blog post](https://www.sparkfun.com/news/2814), the magnetometer isn't the "_star of the show_" and you may want to look at seperate magnetometer. The magnetometer also isn't tilt compensated by default (with the example firmware code).
